# frozen_string_literal: true

source "https://rubygems.org"

repo_name = "Brightcoders-Bootcamps/kata-06-the-gilded-rose-b-team002-kata06.git"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rspec"
gem 'rake'
gem 'rubycritic'
gem 'rubycritic-small-badge', :require => false
gem 'sandi_meter'